version: "3.8"
    
services:  
  influxdb:
    image: influxdb:alpine

    ports:
      - '8086:8086'
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=$DOCKER_INFLUXDB_INIT_MODE
      - DOCKER_INFLUXDB_INIT_USERNAME=$DOCKER_INFLUXDB_INIT_USERNAME
      - DOCKER_INFLUXDB_INIT_PASSWORD=$DOCKER_INFLUXDB_INIT_PASSWORD
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=$DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
      - DOCKER_INFLUXDB_INIT_ORG=$DOCKER_INFLUXDB_INIT_ORG
      - DOCKER_INFLUXDB_INIT_BUCKET=$DOCKER_INFLUXDB_INIT_BUCKET
    networks:
        - default

  telegraf:
    image: telegraf:alpine
    container_name: telegraf
    depends_on: 
      - influxdb
    volumes:
        - type: bind
          source: ./telegraf/mytelegraf.conf
          target: /etc/telegraf/telegraf.conf
    networks:
      - default
    environment:
      - INFLUX_TOKEN=$DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
  
  grafana:
    image: grafana/grafana-enterprise:main
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
      - type: bind
        source: ./grafana-provisioning/
        target: /etc/grafana/provisioning
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=$GRAFANA_USERNAME
      - GF_SECURITY_ADMIN_PASSWORD=$GRAFANA_PASSWORD
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=$DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
    networks:
        - default
        
volumes:
  influxdb-storage:
  grafana-storage:
  
networks:
    default:
        name: iControl-Network
